#!/bin/bash

set -e

fail() {
  echo -e "$@"
  exit 1
}

run_swarm() {
  local java=${JAVA?JAVA is required}
  local swarm_jar=${JSWARM_JAR?JSWARM_JAR is required}

  [[ -x $java ]] || (fail "${java} is not executable")
  [[ -f $swarm_jar ]] || (fail "${swarm_jar} not accessible")

  declare -a cmd

  cmd=("$java")
  if [[ -n $JAVA_ARGS ]]; then
    declare -a java_args_tmp
    IFS=" " read -r -a java_args_tmp <<< "$JAVA_ARGS"
    cmd+=("${java_args_tmp[@]}")
  fi
  cmd+=(-jar "$JSWARM_JAR")
  [[ -n $JSWARM_MODE ]] && cmd+=(-mode "$JSWARM_MODE")
  [[ -n $JSWARM_EXECUTORS ]] && cmd+=(-executors "$JSWARM_EXECUTORS")
  [[ -n $JSWARM_USERNAME ]] && cmd+=(-username "$JSWARM_USERNAME")
  [[ -n $JSWARM_PASSWORD ]] && cmd+=(-passwordEnvVariable JSWARM_PASSWORD)
  [[ -n $JSWARM_AGENT_NAME ]] && cmd+=(-name "$JSWARM_AGENT_NAME")
  [[ -n $JSWARM_MASTER_URL ]] && cmd+=(-master "$JSWARM_MASTER_URL")
  [[ -n $JSWARM_LABELS ]] && cmd+=(-labels "$JSWARM_LABELS")
  [[ -n $JSWARM_FSROOT ]] && cmd+=(-fsroot "$JSWARM_FSROOT")
  [[ $JSWARM_DISABLE_CLIENTS_UNIQUE_ID == true ]] \
    && cmd+=(-disableClientsUniqueId)
  [[ $JSWARM_DISABLE_SSL_VERIFICATION == true ]] \
    && cmd+=(-disableSslVerification)
  [[ $JSWARM_DELETE_EXISTING_CLIENTS == true ]] \
    && cmd+=(-deleteExistingClients)
  [[ -n $JSWARM_DESCRIPTION ]] && cmd+=(-description "$JSWARM_DESCRIPTION")
  [[ -n $JSWARM_TUNNEL ]] && cmd+=(-tunnel "$JSWARM_TUNNEL")
  [[ -n $JSWARM_AUTO_DISCOVERY_ADDRESS ]] &&
    cmd+=(-autoDiscoveryAddress "$JSWARM_AUTO_DISCOVERY_ADDRESS")

  if [[ -n "$JSWARM_TOOL_LOCATIONS" ]]; then
    for t in $JSWARM_TOOL_LOCATIONS; do
      cmd+=(--toolLocation "$t")
    done
  fi

  if [[ -n $JSWARM_OTHER_ARGS ]]; then
    declare -a jswarm_other_args_tmp
    IFS=" " read -r -a jswarm_other_args_tmp <<< "$JSWARM_OTHER_ARGS"
    cmd+=("${jswarm_other_args_tmp[@]}")
  fi

  [[ ${#@} -gt 0 ]] && cmd+=("$@")

  # display swarm cli invocation
  set -x
  "${cmd[@]}"
}

run_swarm "$@"

# vim: tabstop=2 shiftwidth=2 expandtab
